# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.2
loader_version=0.19.5
# Mod Properties
mod_version=2.3.1
maven_group=org.sophia
archives_base_name=Slate_Work
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.116.17+1.21.1

paucal_version = 0.7.3-pre-27
hex_casting = 0.12.0-devel-pre-53
cloth_config = 11.1.136
patchouli_version = 93
cardinal_components_version = 5.2.3
inline_version = 1.2.2
# :clueless:
#hex_pose_version = 1.0.0
more_iotas_version = 0.1.2
trinkets_version=3.7.0